"""add_expires_at_to_reservas

Revision ID: 75cb16d1c0cd
Revises: 7a9fe6e18817
Create Date: 2026-01-03 23:52:23.200055

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75cb16d1c0cd"
down_revision: str | Sequence[str] | None = "7a9fe6e18817"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reservas", sa.Column("expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservas", "expires_at")
    # ### end Alembic commands ###
